### ISSUE TITLE
Generate config from CLI

### ISSUE THREAD

**Issue by psychomario** [psychomario/PyPXE#113]
Would a `-w` (or similar) option which dumps out the effective config to a new file be welcome?

For me at least, I change CLI options until I have a working config. It would be slow going translating this into JSON, and should be relatively easy to add a flag to export the config to a new file. The only issue I forsee is that the saved json config would likely not be very pretty, like our example configs.

**Comment by mmattioli** [comment]
I don't really see this as useful since we already provide a template/example configuration JSON file. Realistically, one could just open the file with vim and edit it on the fly while they keep re-running PyPXE in another terminal if they really need to fine-tune the configuration. Nothing we have in our configuration is mind-blowlingly difficult to comprehend or adjust anyway.

**Comment by psychomario** [comment]
Fair enough. I suppose the config starts with the same defaults anyway.
