### ISSUE TITLE
Buffer too small for tools.t00 of ESXi6.7.0

### ISSUE THREAD

**Issue by marrotte** [psychomario/PyPXE#160]
![screen shot 2018-05-11 at 3 45 53 pm](https://user-images.githubusercontent.com/19251/39943881-83c77dfc-5532-11e8-9d74-e02c6cdaeeea.png)

No errors from PyPXE.  This is during TFTP process.  TOOLS.T00 is the biggest file at 178M.

**Comment by psychomario** [comment]
178Mb is larger than TFTP can support with a standard block size of 512 bytes. Is this a supported installation method?

**Comment by marrotte** [comment]
Yeah.  It's supported here:  

https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/techpaper/vsphere-esxi-vcenter-server-60-pxe-boot-esxi.pdf

But, I see your point and how the TFTP code is tightly coupled with the 2-byte int block ID.  I switched from TFTP to HTTP and got it working.

Thanks for the feedback and sweet PXE server.

**Comment by psychomario** [comment]
I'm a little unsure how this is actually supposed to work, IIRC we've implemented blockid wraparound if supported by the client but that may not be working in this case.

Since it is not recommended to use TFTP for files of this size anyway and you've managed to get it working with HTTP I will close this issue.
